service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  # using API Gateway v2 (HTTP API)
  httpApi:
    cors: true

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: GET
  getProductById:
    handler: handler.getProductById
    events:
      - httpApi:
          path: /products/{productId}
          method: GET

plugins:
  - serverless-esbuild
  - serverless-offline
