service: authorization-service
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

